In [2]:
import numpy as np

np.zeros(2)

array([0., 0.])

In [3]:
np.zeros((2,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [4]:
# 1로 채워진 ndarray객체 생성 ==> ones()
np.ones(10), np.ones(10, dtype=np.int32), np.ones((2,3), dtype=np.bool_)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[ True,  True,  True],
        [ True,  True,  True]]))

In [5]:
np.random.randint(1,5,(3,10))

array([[3, 2, 4, 3, 3, 2, 3, 1, 2, 3],
       [1, 4, 2, 2, 2, 3, 1, 2, 3, 3],
       [2, 1, 1, 3, 1, 3, 1, 1, 3, 3]])

In [6]:
np.random.rand(5,2), np.random.rand(3)

(array([[0.77837681, 0.71356694],
        [0.74758625, 0.2818569 ],
        [0.66944901, 0.50732433],
        [0.33841135, 0.00313397],
        [0.29707483, 0.56015624]]),
 array([0.75746794, 0.72694646, 0.11995221]))

In [7]:
np.random.seed(123)

In [8]:
data=np.random.sample(10)
data

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [10]:
data.max(), data.argmax()

(0.9807641983846155, 6)